### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LogWell** [vchoutas/torch-mesh-isect#13] opened 2019-08-31 07:12 UTC
Sorry to bother you again, may I ask how to solve this problem?

**Comment by w-m** [comment] 2019-09-20 18:14
Check out the discussion in https://github.com/vchoutas/smplify-x/issues/3, this is probably related to the environment, PyTorch installation.

I can reproduce the segfault by using it with a PyTorch installed through `pip install pytorch==1.1.0` on Ubuntu 18.04 with CUDA 10.0. I seem to have got this pip PyTorch version accidentally by installing https://github.com/nghorbani/human_body_prior

When using conda, the problem seems to be resolved by installing pytorch from the pytorch channel:
`conda install pytorch=1.1.0 torchvision cudatoolkit=10.0 -c pytorch`

For pip solutions, see the thread cited above.

**Closed** 2019-10-02 14:41 UTC
